emr:
  config:
    name: "BCEN_SCR_BASE"
    version: "emr-5.23.1"
    primaryNode:
      instanceType: "m5.2xlarge"
      instanceCount: 1
      disk_type: "gp2"
      disk_size: 200
    slaveNodes:
      instanceType: "m5.4xlarge"
      instanceCount: 5
      disk_type: "gp2"
      disk_size: 300
    tags:
      "SPC:BILLING:VN": "CI"
      "SPC:BILLING:CENTROCUSTO": "D00306001"
      "SPC:BILLING:PROJETO": "PARCERIA_BCSCR"
      "SPC:BILLING:PRODUTO": "INSUMO_CADPOS"
      "SPC:AMBIENTE:TIPO": "PRD"
      "SPC:AMBIENTE:SERVICO": "EMR"
      "SPC:AMBIENTE:DATACRIACAO": "2023-06-19"
      "SPC:AMBIENTE:AREA": "ENG_DD"