spark:
  submit:
    name: "[BACEN SCR]-Batch Remessa"
    main_file_name: "/emr/scala_source/scr-remessa-batch-1.0-SNAPSHOT.jar"
    master: "yarn"
    class: "org.spcbrasil.cadastropositivo.bacen.driver.RemessaBatch"
    parameters:
      - ""
    deploy:
      mode: "cluster"
    conf:
      - "spark.yarn.appMasterEnv.SCALA_ENV=aws_dev"
      - "spark.sql.crossJoin.enabled=true"
      - "spark.sql.session.timeZone=UTC"
      - "spark.dynamicAllocation.enabled=true"
      - "spark.dynamicAllocation.executorIdleTimeout=2m"
      - "spark.dynamicAllocation.minExecutors=1"
      - "spark.dynamicAllocation.maxExecutors=3"
      - "spark.executor.memory=5g"
      - "spark.executor.memoryOverhead=1g"
      - "spark.driver.memory=4g"
      - "spark.driver.core=2"
      - "spark.executor.cores=2"
      - "spark.sql.shuffle.partitions=1000"
      - "spark.stage.maxConsecutiveAttempts=20"
      - "spark.shuffle.io.numConnectionsPerPeer=10"
      - "spark.network.timeout=200"
      - "spark.rpc.io.serverTreads=16"
      - "spark.unsafe.sorter.spill.reader.buffer.size=2048k"
      - "spark.shuffle.file.buffer=2048k"
      - "spark.io.compression.lz4.blockSize=512k"
      - "spark.shuffle.service.index.cache.size=2048"
      - "spark.shuffle.compress=true"
      - "spark.shuffle.io.backLog=256" 
      - "spark.memory.storageFraction=0.3" 
      - "spark.driver.maxResultSize=0" 
      - "spark.speculation=true" 
      - "spark.speculation.multiplier=30" 
      - "spark.yarn.maxAppAttempts=1" 
      - "spark.sql.codegen.wholeStage=false" 
      - "spark.sql.sources.partitionOverwriteMode=dynamic" 
      - "spark.serializer=org.apache.spark.serializer.KryoSerializer" 
      - "spark.executor.extraJavaOptions=-XX:ParallelGCThreads=4 -XX:+UseParallelGC"
    jars:
      - "aws-java-sdk-1.12.30.jar"
      - "aws-java-sdk-core-1.12.30.jar"
      - "aws-java-sdk-s3-1.12.30.jar"
      - "delta-core_2.11-0.6.1.jar"
      - "commons-lang3-3.10.jar"
      - "config-1.4.0.jar"
      - "spc-log-0.0.1-SNAPSHOT.jar"
      - "spark-xml_2.11-0.5.0.jar"